# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CODINGDOSA Blog
email: hsnks100@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hsnks100.github.io" # the base hostname & protocol for your site
github_username:  hsnks100
disqus_shortname: codingdosa_dq

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      ["newpost", "publish", "start", "stop"]
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

# Plugins
whitelist: []
gems:
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-feed
- jekyll-paginate

# Conversion
markdown:    kramdown
lsi:         false
excerpt_separator: "\n\n"

# Serving
detach:  false
port:    4000
host:   0.0.0.0
baseurl: "" # does not include hostname

# Outputting
permalink:     /post/:year-:month-:day-:title.html
paginate:      100
paginate_path: "/page:num"
timezone:      "Asia/Seoul"
quiet:         true
defaults:      []

# Markdown Processors
kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     2..3
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
